## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key

gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("cities_d1.csv")
city_data_df.head(20)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Linxia,CN,35.6003,103.2064,267.27,82,94,0.42
1,1,Samarai,PG,-10.6167,150.6667,300.91,74,100,2.92
2,2,Rikitea,PF,-23.1203,-134.9692,299.90,69,33,5.30
3,3,Vaini,TO,-21.2000,-175.2000,299.15,89,75,3.09
4,4,Ushuaia,AR,-54.8000,-68.3000,280.15,61,75,11.83
5,5,George,ZA,-33.9630,22.4617,292.15,94,75,2.06
6,6,Mahebourg,MU,-20.4081,57.7000,297.15,83,20,3.09
7,7,Jamestown,US,42.0970,-79.2353,275.37,93,90,5.24
8,8,Jiayuguan,CN,39.8167,98.3000,264.97,79,90,1.96
9,9,Byron Bay,AU,-28.6500,153.6167,295.15,94,14,2.69
10,10,Kaitangata,NZ,-46.2817,169.8464,290.37,66,100,1.77
11,11,Moron,AR,-34.6534,-58.6198,307.04,51,90,3.60
12,12,Hilo,US,19.7297,-155.0900,297.15,73,90,4.63
13,13,Barrow,US,71.2906,-156.7887,250.15,77,90,2.57
14,14,Hermanus,ZA,-34.4187,19.2345,290.93,83,6,2.28
15,15,Cherskiy,RU,68.7500,161.3000,235.60,81,97,1.39
16,16,Port Alfred,ZA,-33.5906,26.8910,293.71,95,87,1.34
17,17,Robertsport,LR,6.7533,-11.3686,299.79,81,0,4.38
18,18,Thompson,CA,55.7435,-97.8558,253.15,65,40,1.54
19,19,Katsuura,JP,35.1333,140.3000,281.15,87,75,2.57

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 80
What is the maximum temperature you would like for your trip? 90

In [5]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Filter the dataset to find the cities that fit the criteria.
#preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \(city_data_df["Max Temp"] >= min_temp)]
#preferred_cities_df.head(10)
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.count()

City_ID       588
City          588
Country       585
Lat           588
Lng           588
Max Temp      588
Humidity      588
Cloudiness    588
Wind Speed    588
dtype: int64

In [6]:
preferred_cities2_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp)]
preferred_cities2_df.count()

City_ID       0
City          0
Country       0
Lat           0
Lng           0
Max Temp      0
Humidity      0
Cloudiness    0
Wind Speed    0
dtype: int64

In [7]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID       588
City          588
Country       585
Lat           588
Lng           588
Max Temp      588
Humidity      588
Cloudiness    588
Wind Speed    588
dtype: int64

In [8]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Linxia,CN,35.6003,103.2064,267.27,82,94,0.42
1,1,Samarai,PG,-10.6167,150.6667,300.91,74,100,2.92
2,2,Rikitea,PF,-23.1203,-134.9692,299.90,69,33,5.30
3,3,Vaini,TO,-21.2000,-175.2000,299.15,89,75,3.09
4,4,Ushuaia,AR,-54.8000,-68.3000,280.15,61,75,11.83
...,...,...,...,...,...,...,...,...,...
583,583,Gamba,GA,-2.6500,10.0000,298.84,87,100,1.50
584,584,Porto Novo,BJ,6.4965,2.6036,302.15,79,0,5.14
585,585,Leninskoye,KZ,41.7589,69.3864,272.15,86,0,1.03
586,586,Simmerath,DE,50.6000,6.3000,275.37,93,75,4.12
587,587,Jinhua,CN,29.1078,119.6547,280.94,86,91,1.15

In [9]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

        City Country  Max Temp      Lat       Lng Hotel Name
0     Linxia      CN    267.27  35.6003  103.2064
1    Samarai      PG    300.91 -10.6167  150.6667
2    Rikitea      PF    299.90 -23.1203 -134.9692
3      Vaini      TO    299.15 -21.2000 -175.2000
4    Ushuaia      AR    280.15 -54.8000  -68.3000
5     George      ZA    292.15 -33.9630   22.4617
6  Mahebourg      MU    297.15 -20.4081   57.7000
7  Jamestown      US    275.37  42.0970  -79.2353
8  Jiayuguan      CN    264.97  39.8167   98.3000
9  Byron Bay      AU    295.15 -28.6500  153.6167

In [10]:
from config import g_key

In [11]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    try:   
        # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]

    except(IndexError):
            #print("Hotel not found... skipping.")
        pass

In [12]:
hotels

{'html_attributions': [],
 'next_page_token': 'ATtYBwJ8BNci7yO5zewG-A3AkSy3fnwDyJEZIKtSX-XriBU59m8x1hXh0U4MwLMuTKUW6FMCAvFdYZziSsv20-NinczVlwBaqSZenY3pG2aISfQVNc0FGSTIs05cn2-d2CjJmE0sPTRBx7Dy4p-n607tT5m_Xm2HFAINgZibMu0BNRSjNCGRtwdTCD5Zkqk2FvUoABaFg97SCz_o6OU2TxbD0uWBc83WGLWJSFKNzlzTm3aRol692Ntp4OmMqpqwGGCjcfFiD-eNYJo3Q1fHqntWbs0fac8EBfeFMJfAEET3nWIHb6ii9NOSYrT1yl9WUBolgWsSvg8dHnGYKQwd1ORlZ_-jbAt_DTE3N41PPmqEFbQ8Z0tQ4g2WmdLpUGX1ZjvV2BVMziF-HPpe3ftWCzKocQ4mBw95YoASFwS96K-kfUAxqodMnafWiPE30MF4cljhSSwtEdYPZg',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.1187926, 'lng': 119.6266276},
    'viewport': {'northeast': {'lat': 29.1201685802915,
      'lng': 119.6279951302915},
     'southwest': {'lat': 29.1174706197085, 'lng': 119.6252971697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Yayi Hotel',
   'place_id': 'ChIJGetcoGoSSTQRgZKQZaxkjpo',
   'reference': 'ChIJGetcoGoSSTQRgZKQZaxkjpo',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': 'No. 52, You Yi Lu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.087967, 'lng': 119.6449},
    'viewport': {'northeast': {'lat': 29.0893233802915,
      'lng': 119.6461627802915},
     'southwest': {'lat': 29.0866254197085, 'lng': 119.6434648197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Narada Hotel',
   'photos': [{'height': 2988,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117920740787431512759">김영호</a>'],
     'photo_reference': 'ATtYBwKixfIjriBTloWfE71SfsOkng7E7RpfKE2VNrRzlP4nfwo0c6dj3FU17uu5tMDZ_v3QFP3J8wY9NH5Jti2oL2MPYVRLT8i4dOm9fwWWQGORwP5tIcawWBm6-4Lpfx1brF3UzH590SwU9nws9iH-y_Q7awqMwV3jKOMuGrOz6JAc6JO-',
     'width': 5312}],
   'place_id': 'ChIJkb8vRoERSTQR7TtqgzOjdwc',
   'plus_code': {'compound_code': '3JQV+5X Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX3JQV+5X'},
   'rating': 4.5,
   'reference': 'ChIJkb8vRoERSTQR7TtqgzOjdwc',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 11,
   'vicinity': '金华国贸大厦, 369 Shuang Xi Xi Lu, Wucheng Qu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.0814639, 'lng': 119.655369},
    'viewport': {'northeast': {'lat': 29.0828399302915,
      'lng': 119.6567119802915},
     'southwest': {'lat': 29.0801419697085, 'lng': 119.6540140197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Elan Hotel Jinhua South Bayi Street',
   'place_id': 'ChIJFfuLgXkRSTQR7o1U4KU4pTU',
   'plus_code': {'compound_code': '3MJ4+H4 Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX3MJ4+H4'},
   'reference': 'ChIJFfuLgXkRSTQR7o1U4KU4pTU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '585 Li Yu Lu, Wucheng Qu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.0907803, 'lng': 119.6533116},
    'viewport': {'northeast': {'lat': 29.0921150302915,
      'lng': 119.6545608802915},
     'southwest': {'lat': 29.0894170697085, 'lng': 119.6518629197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Elan Jinhua Jiangnan Yintai',
   'place_id': 'ChIJAQAQm9UTSTQRJC3DGVdIR0M',
   'plus_code': {'compound_code': '3MR3+88 Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX3MR3+88'},
   'reference': 'ChIJAQAQm9UTSTQRJC3DGVdIR0M',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': 'Ba Yi Nan Jie 69 Hao Da Lou, Wucheng Qu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.085777, 'lng': 119.6645159},
    'viewport': {'northeast': {'lat': 29.0870303302915,
      'lng': 119.6657542802915},
     'southwest': {'lat': 29.08433236970851, 'lng': 119.6630563197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': '东阳市横店怡峰128连锁酒店',
   'place_id': 'ChIJVVUJX2IRSTQR1Un--KN6QIA',
   'plus_code': {'compound_code': '3MP7+8R Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX3MP7+8R'},
   'reference': 'ChIJVVUJX2IRSTQR1Un--KN6QIA',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': 'No. 11 Dongyong Road, Hendian Town, Dongyang'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.0699623, 'lng': 119.6569658},
    'viewport': {'northeast': {'lat': 29.0713124802915,
      'lng': 119.6583334302915},
     'southwest': {'lat': 29.0686145197085, 'lng': 119.6556354697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Jincheng International Hotel',
   'place_id': 'ChIJ9yl8cnMRSTQRhYg1mcqeMqE',
   'plus_code': {'compound_code': '3M94+XQ Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX3M94+XQ'},
   'rating': 4,
   'reference': 'ChIJ9yl8cnMRSTQRhYg1mcqeMqE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1,
   'vicinity': '金华, Ba Yi Nan Jie, Wucheng Qu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.11022999999999, 'lng': 119.639107},
    'viewport': {'northeast': {'lat': 29.11154473029149,
      'lng': 119.6404636802915},
     'southwest': {'lat': 29.1088467697085, 'lng': 119.6377657197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Guiyun Hotel',
   'place_id': 'ChIJM7W7RDcSSTQRRzLhdqfZBY8',
   'plus_code': {'compound_code': '4J6Q+3J Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX4J6Q+3J'},
   'reference': 'ChIJM7W7RDcSSTQRRzLhdqfZBY8',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '158 Pu Feng Lu, Wucheng Qu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.0746242, 'lng': 119.6607041},
    'viewport': {'northeast': {'lat': 29.0759787302915,
      'lng': 119.6620874302915},
     'southwest': {'lat': 29.0732807697085, 'lng': 119.6593894697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Xincheng Hotel',
   'place_id': 'ChIJ5y_sznERSTQR39EKIR3SP6k',
   'plus_code': {'compound_code': '3MF6+R7 Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX3MF6+R7'},
   'reference': 'ChIJ5y_sznERSTQR39EKIR3SP6k',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '32 Lai Fu Jie, Wucheng Qu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.0725888, 'lng': 119.6398907},
    'viewport': {'northeast': {'lat': 29.0738928802915,
      'lng': 119.6412443302915},
     'southwest': {'lat': 29.0711949197085, 'lng': 119.6385463697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Loong Boutique Hotel',
   'place_id': 'ChIJDZrrcpgRSTQRQKVEEVNQQ4k',
   'plus_code': {'compound_code': '3JFQ+2X Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX3JFQ+2X'},
   'reference': 'ChIJDZrrcpgRSTQRQKVEEVNQQ4k',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '龙腾居家大厦, 428 Dong Zhai Lu, Wucheng Qu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.073569, 'lng': 119.627325},
    'viewport': {'northeast': {'lat': 29.0749469302915,
      'lng': 119.6285995802915},
     'southwest': {'lat': 29.0722489697085, 'lng': 119.6259016197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': '金华豪森假日花园大酒店',
   'place_id': 'ChIJu-S5jb8RSTQRFVEQ60uRJ80',
   'plus_code': {'compound_code': '3JFG+CW Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX3JFG+CW'},
   'reference': 'ChIJu-S5jb8RSTQRFVEQ60uRJ80',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '1 Jin Qu Lu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.082359, 'lng': 119.649956},
    'viewport': {'northeast': {'lat': 29.0837337802915,
      'lng': 119.6514673802915},
     'southwest': {'lat': 29.0810358197085, 'lng': 119.6487694197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Relax Hotel',
   'place_id': 'ChIJw6F8eHgRSTQRmgQrU5p8Ido',
   'plus_code': {'compound_code': '3JJX+WX Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX3JJX+WX'},
   'reference': 'ChIJw6F8eHgRSTQRmgQrU5p8Ido',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '婺城区李渔路888号世贸中心C座, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.100795, 'lng': 119.660912},
    'viewport': {'northeast': {'lat': 29.1021083302915,
      'lng': 119.6621029302915},
     'southwest': {'lat': 29.0994103697085, 'lng': 119.6594049697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Home Inn',
   'place_id': 'ChIJ1Udthc8TSTQR-4i-D8ulzSE',
   'plus_code': {'compound_code': '4M26+89 Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX4M26+89'},
   'reference': 'ChIJ1Udthc8TSTQR-4i-D8ulzSE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '173 Sheng Li Jie, Wucheng Qu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.10921800000001, 'lng': 119.637957},
    'viewport': {'northeast': {'lat': 29.1106617302915,
      'lng': 119.6392769802915},
     'southwest': {'lat': 29.1079637697085, 'lng': 119.6365790197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': '7 Days Inn Station Plaza Branch',
   'place_id': 'ChIJ9xcCBDoSSTQRdd4qR1hhyew',
   'plus_code': {'compound_code': '4J5Q+M5 Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX4J5Q+M5'},
   'rating': 5,
   'reference': 'ChIJ9xcCBDoSSTQRdd4qR1hhyew',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1,
   'vicinity': '273 Di Er Lu, Wucheng Qu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.109164, 'lng': 119.63772},
    'viewport': {'northeast': {'lat': 29.1106070802915,
      'lng': 119.6390401802915},
     'southwest': {'lat': 29.1079091197085, 'lng': 119.6363422197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Shuanglong Scenic Area Tourism Reception Center',
   'place_id': 'ChIJOzcbBToSSTQRnTTPRV5dAjA',
   'plus_code': {'compound_code': '4J5Q+M3 Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX4J5Q+M3'},
   'reference': 'ChIJOzcbBToSSTQRnTTPRV5dAjA',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '289 Di Er Lu, Wucheng Qu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.107724, 'lng': 119.634976},
    'viewport': {'northeast': {'lat': 29.1089517802915,
      'lng': 119.6363538802915},
     'southwest': {'lat': 29.1062538197085, 'lng': 119.6336559197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Jiaheng Hotel',
   'place_id': 'ChIJ45S0qzsSSTQRMG-q_OHlLc0',
   'plus_code': {'compound_code': '4J5M+3X Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX4J5M+3X'},
   'rating': 4,
   'reference': 'ChIJ45S0qzsSSTQRMG-q_OHlLc0',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1,
   'vicinity': '898 Ren Min Xi Lu, Wucheng Qu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.085278, 'lng': 119.652577},
    'viewport': {'northeast': {'lat': 29.0866401802915,
      'lng': 119.6539984802915},
     'southwest': {'lat': 29.08394221970851, 'lng': 119.6513005197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Zi Yang Hao Ting Hotel',
   'place_id': 'ChIJT9E8LH8RSTQR3N4CmyUMO9E',
   'plus_code': {'compound_code': '3MP3+42 Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX3MP3+42'},
   'reference': 'ChIJT9E8LH8RSTQR3N4CmyUMO9E',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '-A, 572 Bin Hong Lu, Wucheng Qu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.08107399999999, 'lng': 119.656156},
    'viewport': {'northeast': {'lat': 29.0822222302915,
      'lng': 119.6575436802915},
     'southwest': {'lat': 29.0795242697085, 'lng': 119.6548457197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Motel 168',
   'place_id': 'ChIJizDbKHoRSTQRYT5tLismXiU',
   'plus_code': {'compound_code': '3MJ4+CF Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX3MJ4+CF'},
   'rating': 3,
   'reference': 'ChIJizDbKHoRSTQRYT5tLismXiU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1,
   'vicinity': '58 Yang Guang Lu, Wucheng Qu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.0842107, 'lng': 119.6537417},
    'viewport': {'northeast': {'lat': 29.0855984302915,
      'lng': 119.6553432302915},
     'southwest': {'lat': 29.0829004697085, 'lng': 119.6526452697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Home Inn Bayi South Street',
   'place_id': 'ChIJjXSZMHkRSTQRvPqmLTnZn3w',
   'plus_code': {'compound_code': '3MM3+MF Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX3MM3+MF'},
   'rating': 3,
   'reference': 'ChIJjXSZMHkRSTQRvPqmLTnZn3w',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1,
   'vicinity': '458 Ba Yi Nan Jie, Wucheng Qu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.081575, 'lng': 119.641692},
    'viewport': {'northeast': {'lat': 29.0829090802915,
      'lng': 119.6429396802915},
     'southwest': {'lat': 29.0802111197085, 'lng': 119.6402417197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': '锦江之星金华宾虹路店',
   'place_id': 'ChIJydKjL5sRSTQR1ZXwnOcHeC0',
   'plus_code': {'compound_code': '3JJR+JM Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX3JJR+JM'},
   'reference': 'ChIJydKjL5sRSTQR1ZXwnOcHeC0',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '329 Yong Kang Jie, Wucheng Qu, Jinhua Shi'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 29.1152462, 'lng': 119.6430663},
    'viewport': {'northeast': {'lat': 29.11660093029149,
      'lng': 119.6443185802915},
     'southwest': {'lat': 29.11390296970849, 'lng': 119.6416206197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Jinhuan Hotel',
   'place_id': 'ChIJQeTdk0kSSTQRVda-m_HJgPc',
   'plus_code': {'compound_code': '4J8V+36 Wucheng District, Jinhua, Zhejiang, China',
    'global_code': '7PXX4J8V+36'},
   'reference': 'ChIJQeTdk0kSSTQRVda-m_HJgPc',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '后城里大街351号, Hou Cheng Li Jie, Wucheng Qu, Jinhua Shi'}],
 'status': 'OK'}

In [13]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Linxia,CN,267.27,35.6003,103.2064,GreenTree Inn Linxia Autonomous Prefecture Lin...
1,Samarai,PG,300.91,-10.6167,150.6667,Nuli Sapi
2,Rikitea,PF,299.90,-23.1203,-134.9692,Pension Maro'i
3,Vaini,TO,299.15,-21.2000,-175.2000,Keleti Beach Resort
4,Ushuaia,AR,280.15,-54.8000,-68.3000,Albatros Hotel
...,...,...,...,...,...,...
583,Gamba,GA,298.84,-2.6500,10.0000,
584,Porto Novo,BJ,302.15,6.4965,2.6036,Tour Eiffel Hotel Benin
585,Leninskoye,KZ,272.15,41.7589,69.3864,
586,Simmerath,DE,275.37,50.6000,6.3000,Erlebnislokal
587,Jinhua,CN,280.94,29.1078,119.6547,Yayi Hotel

In [14]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df= hotel_df.dropna( axis=0)
clean_hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Linxia,CN,267.27,35.6003,103.2064,GreenTree Inn Linxia Autonomous Prefecture Lin...
1,Samarai,PG,300.91,-10.6167,150.6667,Nuli Sapi
2,Rikitea,PF,299.90,-23.1203,-134.9692,Pension Maro'i
3,Vaini,TO,299.15,-21.2000,-175.2000,Keleti Beach Resort
4,Ushuaia,AR,280.15,-54.8000,-68.3000,Albatros Hotel
5,George,ZA,292.15,-33.9630,22.4617,Protea Hotel by Marriott George King George
6,Mahebourg,MU,297.15,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
7,Jamestown,US,275.37,42.0970,-79.2353,Hampton Inn & Suites Jamestown
8,Jiayuguan,CN,264.97,39.8167,98.3000,Jiugang Hotel - Jiayuguan
9,Byron Bay,AU,295.15,-28.6500,153.6167,Backpackers Inn on the Beach

In [15]:
# 8a. Create the output File (CSV)
# Create the output file (CSV).
output_data_file = "hotels_d2.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [16]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = str(clean_hotel_df[["City","Country","Max Temp"]])

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [17]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))